# Generated by Django 3.2.9 on 2021-11-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papers',
            options={'verbose_name_plural': 'Papers'},
        ),
    ]
